### ISSUE TITLE
pull latest XR/XE models at install

### ISSUE THREAD

**Issue by tomasdking** [CiscoDevNet/yang-explorer#28]
It would make sense to pull the latest models at install rather than having to pull and install these manually. An automated way to pull and compile at install would make this task much easier.

**Comment by pgohite** [comment]
Since yang-explorer can be used for any netconf agent it is difficult to figure out which models user wants to load. We have provided different methods to make it flexible.

- Upload manually from UI Yang Models Tab -> Workspace -> Add
- Upload from device from UI Yang Models Tab -> Device -> (select device) -> sync
- Upload from command line 1) upload from local directory 2) upload from git

Please see upload section for more detail.

**Comment by pgohite** [comment]
Please let me know if you have any suggestion to make it more user friendly.
